name: Android CI

on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    name: Publish Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

#
#      - name: Upload to Central
#        env:
#          SOME_SECRET: ${{ secrets.SOME_VALUE }}
#        run: |
#          ./gradlew publishAllPublicationsToSonatypeRepository

  release:
    name: Create GitHub Release
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set release name
        run: echo ::set-env name=RELEASE_NAME::$(echo ${GITHUB_REF:11})

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false
